(() => {
  const SAVE = "emberwell.v6";
  const SKIM = 0.42;
  const SHAFTS = ["Peat shaft","Cinder seam","Kiln throat","Ash plug","Nightcoal run","Root vein","Ember cut","Deep latch"];
  const FOES = [{id:"mira",name:"Mira of Soot",power:18},{id:"bram",name:"Bram Wellkin",power:28},{id:"noll",name:"Noll the Tender",power:41},{id:"kesh",name:"Kesh Ashrank",power:58},{id:"iora",name:"Iora Deep",power:79}];
  const BODIES = [{id:"cinderpup",name:"Cinderpup"},{id:"peatling",name:"Peatling"},{id:"kilnmoth",name:"Kilnmoth"},{id:"emberowl",name:"Emberowl"}];
  const RARITIES = [{label:"Common",bonus:0},{label:"Uncommon",bonus:1},{label:"Rare",bonus:2},{label:"Ember",bonus:4}];
  const JOBS = ["wellhand","tender","pitborn"];
  const CROPS = {sparkgrass:{name:"Spark",ms:16000,cinder:18,floor:1},peatroot:{name:"Peat",ms:45000,cinder:48,floor:1},kilnwheat:{name:"Kiln",ms:120000,cinder:110,floor:4},nightcoal:{name:"Night",ms:240000,cinder:220,floor:8}};
  const PACKS = [{id:"spark",name:"Spark Pack",cost:0,gold:160,cinder:50,owned:true},{id:"kindling",name:"Kindling Pack",cost:8,gold:500,cinder:180},{id:"hunter",name:"Hunter Pack",cost:18,gold:1400,cinder:420}];
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const fmt = n => { n = Math.floor(n); return n >= 1e4 ? (n/1e3).toFixed(1)+"k" : String(n); };
  function kinStats(e){const lv=e.lv||1,b=e.bonus||0;return{work:+(0.3+b*0.12+lv*0.08+(e.affinity==="wellhand"?0.2:0)).toFixed(2),tend:+(0.06+b*0.03+lv*0.02+(e.affinity==="tender"?0.08:0)).toFixed(2),atk:Math.floor(8+b*6+lv*4+(e.affinity==="pitborn"?10:0)+(e.power||0)*18),lv};}
  function defaultState(){const now=Date.now();return{gold:48,cinder:36,embers:14,ash:2,floor:1,wellLv:1,luckLv:1,xp:4,wellCache:10,shaft:0,plugged:false,plugHp:40,plugMax:40,plots:[1,2,3,4,5,6,7].map(id=>({id,unlocked:id<4,crop:id===1?"sparkgrass":null,plantedAt:id===1?now-5000:0,doneAt:id===1?now+11000:0})),den:[{id:1,body:"cinderpup",name:"Cinderpup",rarityLabel:"Uncommon",affinity:"wellhand",job:"wellhand",power:0.4,bonus:1,lv:1},{id:2,body:"peatling",name:"Peatling",rarityLabel:"Common",affinity:"pitborn",job:"pitborn",power:0.28,bonus:0,lv:1}],nextId:3,hatchCount:2,lastSeen:now,seed:"sparkgrass",fert:0,packsOwned:["spark"],lastDaily:0,foe:"mira",rank:0,lastFight:0,fights:0,lastLog:"Draw.",ease:{cap:false,hands:0},log:"The well is the mine. Hands cut the shaft. The pit is other dens."};}
  let S = defaultState();
  function load(){try{const raw=localStorage.getItem(SAVE);if(!raw)return;S={...defaultState(),...JSON.parse(raw)};if(!S.den||!S.den.length)S.den=defaultState().den;if(!Array.isArray(S.plots)||S.plots.length<7)S.plots=defaultState().plots;}catch(e){}}
  function save(){S.lastSeen=Date.now();localStorage.setItem(SAVE,JSON.stringify(S));}
  const shaftNeed=()=>24+S.floor*16;
  const plugMax=()=>36+S.floor*14;
  const cutCost=()=>Math.floor(40*Math.pow(1.32,S.floor-1));
  const wellCap=()=>36+S.wellLv*14+(S.ease.cap?24:0);
  const hatchCost=()=>Math.floor(16+S.hatchCount*7);
  const wellCost=()=>Math.floor(28*Math.pow(1.55,S.wellLv-1));
  const shaftName=()=>SHAFTS[(S.floor-1)%SHAFTS.length]+" · F"+S.floor;
  function fullPower(){const extra=S.ease.hands||0;const h=S.den.filter(e=>e.job==="wellhand").reduce((a,e)=>a+kinStats(e).work,0)+extra*0.35;return (2.4+S.wellLv*1.15)*(1+h);}
  function wellPower(){return S.plugged?fullPower()*SKIM:fullPower();}
  function pitPower(){return S.den.filter(e=>e.job==="pitborn").reduce((a,e)=>a+kinStats(e).atk,0);}
  function growBonus(){const t=S.den.filter(e=>e.job==="tender").reduce((a,e)=>a+kinStats(e).tend,0);return Math.max(0.38,1-t);}
  function plugWorkRate(){const h=S.den.filter(e=>e.job==="wellhand").length+(S.ease.hands||0);return 3+h*2.2+S.wellLv;}
  function fillCache(sec){S.wellCache=Math.min(wellCap(),(S.wellCache||0)+wellPower()*sec);if(S.plugged){S.plugHp=Math.max(0,S.plugHp-plugWorkRate()*sec);if(S.plugHp<=0)openFloor("Hands chewed the plug.");}else{S.shaft=Math.min(shaftNeed(),(S.shaft||0)+fullPower()*sec*0.5);if(S.shaft>=shaftNeed()){S.plugged=true;S.plugMax=plugMax();S.plugHp=S.plugMax;S.log="Plug in the shaft. Work it on this tab. Kin skim at 42%.";}}}
  function toast(m){const el=$("#toast");el.textContent=m;el.classList.add("on");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("on"),1500);}
  function show(tab){$$(".view").forEach(v=>v.classList.toggle("on",v.dataset.view===tab));$$("nav button").forEach(b=>b.classList.toggle("on",b.dataset.tab===tab));}
  function tapWell(){const gain=Math.max(3,Math.round((7+S.wellLv*2)*(S.plugged?SKIM:1)));S.gold+=gain;S.xp+=1;if(S.plugged)S.plugHp=Math.max(0,S.plugHp-4-S.wellLv);else S.shaft=Math.min(shaftNeed(),S.shaft+gain*0.7);if(!S.plugged&&S.shaft>=shaftNeed()){S.plugged=true;S.plugMax=plugMax();S.plugHp=S.plugMax;S.log="Plug in the shaft.";}if(S.plugged&&S.plugHp<=0)openFloor("You tapped the plug out.");$("#hand").classList.add("hide");save();renderHud();}
  function collectWell(){const amt=Math.floor(S.wellCache||0);if(amt<1)return toast("Still filling.");S.gold+=amt;S.wellCache=0;toast("+"+fmt(amt)+" gold");save();render();}
  function openFloor(why){S.floor+=1;S.plugged=false;S.shaft=0;S.plugHp=plugMax();S.plugMax=plugMax();S.xp+=10;S.log=why+" Floor "+S.floor+" is open. Full well rate is back.";toast("Floor "+S.floor);}
  function cutPlug(){const c=cutCost();if(S.gold<c)return toast("Need "+fmt(c)+" gold.");S.gold-=c;openFloor("You bought the cut.");save();render();}
  function workPlug(){if(!S.plugged)return toast("No plug yet.");S.plugHp=Math.max(0,S.plugHp-plugWorkRate()*3);if(S.plugHp<=0)openFloor("Hands finished the plug.");save();render();}
  function skipPlug(){if(S.embers<2)return toast("Need 2 embers.");S.embers-=2;openFloor("Paid cut. Shaft dropped.");save();render();}
  function hatch(){const c=hatchCost();if(S.cinder<c)return toast("Need "+c+" cinder.");S.cinder-=c;S.hatchCount+=1;S.xp+=8;const body=BODIES[S.hatchCount%BODIES.length];const r=RARITIES[S.hatchCount%3];const job=JOBS[S.hatchCount%3];S.den.unshift({id:S.nextId++,body:body.id,name:body.name,rarityLabel:r.label,affinity:job,job:null,power:0.22+r.bonus*0.08,bonus:r.bonus,lv:1});toast(body.name+" · "+r.label);save();render();show("you");}
  function assign(id,job){const k=S.den.find(e=>e.id===id);if(!k)return;k.job=k.job===job?null:job;save();render();}
  function levelKin(id){const k=S.den.find(e=>e.id===id);if(!k)return;const c=2+(k.lv||1);if(S.ash<c)return toast("Need "+c+" ash.");S.ash-=c;k.lv=(k.lv||1)+1;save();render();}
  function plantEmpty(){const empties=S.plots.filter(p=>p.unlocked&&!p.crop);if(!empties.length)return toast("No empty bed.");const crop=CROPS[S.seed];if(S.floor<crop.floor)return toast("Need floor "+crop.floor);empties.forEach(plot=>{let ms=Math.floor(crop.ms*growBonus());if(S.fert>0){ms=Math.floor(ms*0.7);S.fert-=1;}plot.crop=S.seed;plot.plantedAt=Date.now();plot.doneAt=Date.now()+ms;});save();render();}
  function harvestRipe(){let n=0;S.plots.forEach(p=>{if(p.crop&&Date.now()>=p.doneAt){S.cinder+=CROPS[p.crop].cinder;p.crop=null;p.plantedAt=0;p.doneAt=0;n+=1;}});if(!n)return toast("Nothing ripe.");toast("+"+n+" harvests");save();render();}
  function harvestOne(id){const p=S.plots.find(x=>x.id===id);if(!p||!p.crop||Date.now()<p.doneAt){if(p&&p.unlocked&&!p.crop){plantOn(p);return;}return;}S.cinder+=CROPS[p.crop].cinder;p.crop=null;p.plantedAt=0;p.doneAt=0;save();render();}
  function plantOn(plot){const crop=CROPS[S.seed];if(S.floor<crop.floor)return toast("Need floor "+crop.floor);let ms=Math.floor(crop.ms*growBonus());if(S.fert>0){ms=Math.floor(ms*0.7);S.fert-=1;}plot.crop=S.seed;plot.plantedAt=Date.now();plot.doneAt=Date.now()+ms;save();render();}
  function unlockPlot(){const locked=S.plots.find(p=>!p.unlocked);if(!locked)return toast("Garden full.");if(S.gold<80)return toast("Need 80 gold.");S.gold-=80;locked.unlocked=true;save();render();}
  function fertilize(){if(S.cinder<8)return toast("Need 8 cinder.");S.cinder-=8;S.fert+=1;toast("Next plants faster");save();render();}
  function foeObj(){return FOES.find(f=>f.id===S.foe)||FOES[0];}
  function fight(){if(!S.den.some(e=>e.job==="pitborn"))return toast("Assign pitborn in You.");const you=pitPower();const them=Math.floor(foeObj().power*(1+S.floor*0.04));const win=you+Math.random()*8>=them;S.fights+=1;S.lastFight=Date.now();if(win){const ash=2+Math.floor(them/20);S.ash+=ash;S.gold+=12+S.floor*4;S.rank+=1;if(S.rank%3===0)S.embers+=1;S.lastLog="Win vs "+foeObj().name+". +"+ash+" ash.";toast("Den stands");}else{S.gold+=4;S.lastLog="Loss vs "+foeObj().name+". Crew lives.";toast("They held");}S.log=S.lastLog;save();render();}
  function rematch(){if(S.embers<1)return toast("Need 1 ember.");S.embers-=1;fight();}
  function buyWell(){const c=wellCost();if(S.gold<c)return toast("Need "+fmt(c));S.gold-=c;S.wellLv+=1;save();render();}
  function buyHands(){if(S.gold<60)return toast("Need 60 gold.");S.gold-=60;S.ease.hands=(S.ease.hands||0)+1;save();render();}
  function buyPack(id){const p=PACKS.find(x=>x.id===id);if(!p||p.owned||S.packsOwned.includes(id))return;if(S.embers<p.cost)return toast("Need "+p.cost+" embers");S.embers-=p.cost;S.gold+=p.gold;S.cinder+=p.cinder;S.packsOwned.push(id);save();render();}
  function buyEase(kind){if(kind==="cap"){if(S.ease.cap)return;if(S.embers<3)return toast("Need 3 embers");S.embers-=3;S.ease.cap=true;toast("Basin holds more");}if(kind==="cut"){if(!S.plugged)return toast("No plug to skip.");skipPlug();return;}if(kind==="fert"){if(S.embers<2)return toast("Need 2 embers");S.embers-=2;S.fert+=3;toast("+3 fert");}if(kind==="ticket"){if(S.embers<2)return toast("Need 2 embers");S.embers-=2;fight();return;}save();render();}
  function claimDaily(){const day=Math.floor(Date.now()/86400000);if(S.lastDaily===day)return toast("Tomorrow");S.lastDaily=day;S.embers+=2;toast("+2 embers");save();render();}
  function nextRipe(){const now=Date.now(),g=S.plots.filter(p=>p.crop&&p.doneAt>now);if(!g.length)return S.plots.some(p=>p.crop&&p.doneAt<=now)?"READY":"";return Math.max(0,Math.ceil((Math.min(...g.map(p=>p.doneAt))-now)/1000))+"s";}
  function cropArt(p){if(!p.unlocked)return"art-hexlock";if(!p.crop)return"art-hexempty";const ready=Date.now()>=p.doneAt;return p.crop==="sparkgrass"?(ready?"art-sparkripe":"art-sparksprout"):(ready?"art-peatripe":"art-peatsprout");}
  function renderHud(){$("#gold").textContent=fmt(S.gold);$("#cinder").textContent=fmt(S.cinder);$("#embersHud").textContent=fmt(S.embers);$("#rateLbl").textContent=S.plugged?"Skim":"Well";$("#rate").textContent=wellPower().toFixed(1)+"/s";$("#floor").textContent="Floor "+S.floor+" · slice 6";const cap=wellCap(),cache=S.wellCache||0;$("#wellFill").style.width=Math.min(100,cache/cap*100)+"%";$("#wellCap").textContent=fmt(cache)+" / "+fmt(cap);const secs=wellPower()>0?Math.ceil(Math.max(0,cap-cache)/wellPower()):0;$("#wellEta").textContent=cache>=cap?"Basin full":secs+"s to fill";$("#collectWell").disabled=cache<1;const need=shaftNeed();const pct=S.plugged?Math.max(0,100-(S.plugHp/(S.plugMax||plugMax())*100)):Math.min(100,(S.shaft/need)*100);$("#depthName").textContent=shaftName();$("#depthPct").textContent=Math.floor(pct)+"%";$("#depthFill").style.width=pct+"%";$("#depthNote").textContent=S.plugged?"Plug. Hands work it here. Skim 42% until it breaks.":"Shaft "+fmt(S.shaft)+" / "+fmt(need)+". Hands cut while gold fills.";const mark=$("#shaftMarks");if(mark)mark.innerHTML="<i style='height:"+pct+"%'></i>";const gate=$("#gate"),ups=$("#wellUps");if(gate&&ups){gate.hidden=!S.plugged;ups.style.display=S.plugged?"none":"grid";}if(S.plugged)$("#plugFill").style.width=Math.max(0,100-pct)+"%";$("#navEta").textContent=nextRipe();$("#navPit").textContent=S.rank?String(S.rank):"";$("#youLv").textContent=1+Math.floor(S.xp/40);$("#youXp").textContent=(S.xp%40)+" / 40 xp";$("#xpBar").style.width=((S.xp%40)/40*100)+"%";}
  function renderWell(){$("#btnWell").innerHTML="<strong>Widen basin</strong><em>"+fmt(wellCost())+" gold</em>";$("#btnHands").innerHTML="<strong>Hire hand</strong><em>60 gold · +"+(S.ease.hands||0)+"</em>";$("#btnCut").innerHTML="<strong>Buy cut</strong><em>"+fmt(cutCost())+" gold</em>";$("#btnWork").innerHTML="<strong>Work plug</strong><em>"+plugWorkRate().toFixed(1)+"/s</em>";$("#btnSkip").innerHTML="<strong>Skip plug</strong><em>2 embers</em>";$("#btnCut").disabled=S.gold<cutCost();$("#btnSkip").disabled=S.embers<2;}
  function renderHearth(){const wrap=$("#plots");wrap.innerHTML="";S.plots.forEach(p=>{const ready=!!(p.crop&&Date.now()>=p.doneAt);const el=document.createElement("button");el.className="hex"+(p.unlocked?"":" locked")+(ready?" ready":"");el.innerHTML="<div class='bed "+cropArt(p)+"'></div><div class='meta'></div>";const meta=el.querySelector(".meta");if(!p.unlocked){meta.innerHTML="<b>Sealed</b>80g";el.onclick=unlockPlot;}else if(!p.crop){meta.innerHTML="<b>Empty</b>";el.onclick=()=>harvestOne(p.id);}else{const left=Math.max(0,Math.ceil((p.doneAt-Date.now())/1000));meta.innerHTML="<b>"+(ready?"Ripe":CROPS[p.crop].name)+"</b>"+(ready?"pull":left+"s");el.onclick=()=>harvestOne(p.id);}wrap.appendChild(el);});const row=$("#seedRow");row.innerHTML="";Object.keys(CROPS).forEach(id=>{const c=CROPS[id],b=document.createElement("button");const locked=S.floor<c.floor;b.className="seed"+(S.seed===id?" on":"");b.disabled=locked;b.innerHTML="<b>"+c.name+"</b><em>"+(locked?"F"+c.floor:Math.round(c.ms/1000)+"s")+"</em>";b.onclick=()=>{S.seed=id;save();renderHearth();};row.appendChild(b);});$("#gardenEta").textContent=nextRipe()||"idle";$("#gardenState").textContent=nextRipe()==="READY"?"Ripe":(S.fert?"Fert x"+S.fert:"Hearth");$("#plantHint").textContent=CROPS[S.seed].name;$("#fertBtn").innerHTML="<strong>Fertilize</strong><em>8 cinder · x"+S.fert+"</em>";$("#expandBtn").innerHTML="<strong>New bed</strong><em>80 gold</em>";$("#expandBtn").disabled=S.gold<80||!S.plots.some(p=>!p.unlocked);}
  function renderPit(){$("#pitRank").textContent=S.rank;const f=foeObj();const you=pitPower();const them=Math.floor(f.power*(1+S.floor*0.04));$("#duel").innerHTML="<div><div class='face'></div><p>Your den<br><b>"+fmt(you)+" atk</b></p></div><div class='vs'>VS</div><div><div class='face'></div><p>"+f.name+"<br><b>"+fmt(them)+" atk</b></p></div>";$("#pitStrip").innerHTML="<span>Rank<b>"+S.rank+"</b></span><span>Fights<b>"+S.fights+"</b></span><span>Ash<b>"+fmt(S.ash)+"</b></span>";const box=$("#foes");box.innerHTML="";FOES.forEach(foe=>{const el=document.createElement("button");el.className="foe"+(S.foe===foe.id?" on":"");el.innerHTML="<b>"+foe.name+"</b><em>"+Math.floor(foe.power*(1+S.floor*0.04))+" atk</em>";el.onclick=()=>{S.foe=foe.id;save();renderPit();};box.appendChild(el);});$("#pitBtn").innerHTML="<strong>Challenge den</strong><em>auto resolve</em>";$("#rematchBtn").innerHTML="<strong>Rematch</strong><em>1 ember</em>";}
  function renderMarket(){$("#ease").innerHTML="<article><b>Bigger basin</b><em>"+(S.ease.cap?"Owned":"3 embers")+"</em><button class='btn' "+(S.ease.cap?"disabled":"")+" data-ease='cap'>Buy</button></article><article><b>Skip this plug</b><em>2 embers</em><button class='btn' data-ease='cut'>Use</button></article><article><b>Fert bundle</b><em>2 embers · 3 uses</em><button class='btn' data-ease='fert'>Buy</button></article><article><b>Extra duel</b><em>2 embers</em><button class='btn' data-ease='ticket'>Fight</button></article>";$$("#ease [data-ease]").forEach(b=>b.onclick=()=>buyEase(b.dataset.ease));const wrap=$("#packs");wrap.innerHTML="";PACKS.forEach(p=>{const owned=p.owned||S.packsOwned.includes(p.id);const el=document.createElement("article");el.className="pack";el.innerHTML="<h3>"+p.name+"</h3><p>+"+fmt(p.gold)+"g · +"+fmt(p.cinder)+"c</p><button class='btn'></button>";const b=el.querySelector("button");b.textContent=owned?"Owned":p.cost+" embers";b.disabled=owned||S.embers<p.cost;b.onclick=()=>buyPack(p.id);wrap.appendChild(el);});}
  function renderYou(){$("#attrs").innerHTML="<div>Well rate<b>"+wellPower().toFixed(1)+"/s</b></div><div>Full rate<b>"+fullPower().toFixed(1)+"/s</b></div><div>Pit ATK<b>"+fmt(pitPower())+"</b></div><div>Ash / rank<b>"+fmt(S.ash)+" · "+S.rank+"</b></div>";$("#hatchBtn").innerHTML="<strong>Hatch Emberkin</strong><em>"+hatchCost()+" cinder</em>";const list=$("#cards");list.innerHTML="";S.den.forEach(e=>{const st=kinStats(e);const el=document.createElement("article");el.className="card";el.innerHTML="<div class='face'></div><div><h4>"+e.name+" · lv"+st.lv+"</h4><small>"+e.rarityLabel+" · "+e.affinity+"</small><div class='nums'>ATK <b>"+st.atk+"</b> WORK <b>"+st.work+"</b> TEND <b>"+st.tend+"</b></div></div><div class='jobs'></div>";const jobs=el.querySelector(".jobs");JOBS.forEach(job=>{const b=document.createElement("button");b.textContent=job;if(e.job===job)b.className="on";b.onclick=()=>assign(e.id,job);jobs.appendChild(b);});const lv=document.createElement("button");lv.className="lvl";lv.textContent="lv "+(2+st.lv)+" ash";lv.onclick=()=>levelKin(e.id);jobs.appendChild(lv);list.appendChild(el);});}
  function render(){renderHud();renderWell();renderHearth();renderPit();renderMarket();renderYou();$("#log").textContent=S.log;}
  let acc=0;
  function loop(ts){if(!loop.last)loop.last=ts;const dt=ts-loop.last;loop.last=ts;acc+=dt;if(acc>220){fillCache(acc/1000);acc=0;renderHud();if($("[data-view=hearth]").classList.contains("on"))renderHearth();if($("[data-view=well]").classList.contains("on")&&S.plugged)renderWell();}requestAnimationFrame(loop);}
  function boot(){load();const elapsed=Math.min(4*3600*1000,Math.max(0,Date.now()-(S.lastSeen||Date.now())));if(elapsed>2000)fillCache(elapsed/1000);save();render();show("well");$("#well-stage").addEventListener("pointerdown",e=>{if(e.target.closest(".collect-btn"))return;e.preventDefault();tapWell();});$("#collectWell").onclick=e=>{e.stopPropagation();collectWell();};$("#btnWell").onclick=buyWell;$("#btnHands").onclick=buyHands;$("#btnCut").onclick=cutPlug;$("#btnWork").onclick=workPlug;$("#btnSkip").onclick=skipPlug;$("#plantAll").onclick=plantEmpty;$("#harvestAll").onclick=harvestRipe;$("#fertBtn").onclick=fertilize;$("#expandBtn").onclick=unlockPlot;$("#pitBtn").onclick=fight;$("#rematchBtn").onclick=rematch;$("#dailyEmber").onclick=claimDaily;$("#hatchBtn").onclick=hatch;$$("#shopTabs b").forEach(b=>b.onclick=()=>{$$("#shopTabs b").forEach(x=>x.classList.toggle("on",x===b));$$(".shop-pane").forEach(p=>p.classList.toggle("on",p.dataset.shop===b.dataset.shop));});$$("nav button").forEach(b=>b.onclick=()=>show(b.dataset.tab));$("#reset").onclick=()=>{localStorage.removeItem(SAVE);localStorage.removeItem("emberwell.v5");S=defaultState();save();render();};requestAnimationFrame(loop);setInterval(save,4000);}
  boot();
})();
