(() => {
const SAVE="emberwell.v9";const CAP=80;
const VEINS=["Ember Heart","Peat Core","Kiln Knot","Ash Crown","Nightcoal","Root Furnace","Deep Cinder","White Heat"];
const SPECIES=[{id:"pup",name:"Cinderpup"},{id:"peat",name:"Peatling"},{id:"moth",name:"Kilnmoth"},{id:"owl",name:"Emberowl"},{id:"fox",name:"Sootfox"},{id:"stoat",name:"Ashstoat"}];
const RARITIES=[{label:"Common",bonus:0,w:54},{label:"Uncommon",bonus:1,w:24},{label:"Rare",bonus:2,w:14},{label:"Ember",bonus:4,w:8}];
const FOES=[{id:"mira",name:"Mira of Soot",power:16},{id:"bram",name:"Bram Wellkin",power:26},{id:"noll",name:"Noll Tender",power:40},{id:"kesh",name:"Kesh Ashrank",power:56},{id:"iora",name:"Iora Deep",power:78}];
const CROPS={sparkgrass:{name:"Spark",ms:18000,cinder:18,floor:1},peatroot:{name:"Peat",ms:48000,cinder:48,floor:1},kilnwheat:{name:"Kiln",ms:130000,cinder:110,floor:4},nightcoal:{name:"Night",ms:260000,cinder:220,floor:8}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>{n=Math.floor(n);return n>=1e4?(n/1e3).toFixed(1)+"k":String(n);};
function pickRarity(luck){const bag=RARITIES.map(r=>({...r,w:r.w+luck*r.bonus}));let t=bag.reduce((a,b)=>a+b.w,0),roll=Math.random()*t;for(const r of bag){roll-=r.w;if(roll<=0)return r;}return bag[0];}
function dpsOf(e){if(!e)return 0;return +((1.4+e.bonus*1.1+(e.lv||1)*0.85+(e.power||0)*4)*(e.mult||1)).toFixed(1);}
function atkOf(e){return Math.floor(dpsOf(e)*6+(e.lv||1)*3);}
function tendOf(e){return +(0.05+(e.bonus||0)*0.03+(e.lv||1)*0.02).toFixed(2);}
function makeKin(p){const spec=p.spec||SPECIES[Math.floor(Math.random()*SPECIES.length)];const r=p.rarity||pickRarity(1);return{id:p.id,spec:spec.id,name:spec.name,rarityLabel:r.label,bonus:r.bonus,power:0.18+r.bonus*0.08+Math.random()*0.12,lv:1,mult:1,job:p.job||null};}
function defaultState(){const now=Date.now();const a=makeKin({id:1,spec:SPECIES[0],rarity:RARITIES[1],job:"well"});const b=makeKin({id:2,spec:SPECIES[1],rarity:RARITIES[0],job:"pit"});return{gold:40,cinder:32,embers:12,ash:3,floor:1,luck:1,xp:4,cache:8,veinHp:90,veinMax:90,den:[a,b],slots:[1,0,0,0,0,0,0,0],nextId:3,hatchCount:2,lastSeen:now,seed:"sparkgrass",lastDaily:0,foe:"mira",rank:0,fights:0,plots:[1,2,3,4,5,6,7].map(id=>({id,unlocked:id<4,crop:id===1?"sparkgrass":null,doneAt:id===1?now+14000:0}));}}
let S=defaultState();
function load(){try{const raw=localStorage.getItem(SAVE);if(!raw)return;S={...defaultState(),...JSON.parse(raw)};if(!S.den||!S.den.length)S.den=defaultState().den;if(!S.slots||S.slots.length!==8)S.slots=[1,0,0,0,0,0,0,0];if(S.cache==null)S.cache=0;}catch(e){}}
function save(){S.lastSeen=Date.now();localStorage.setItem(SAVE,JSON.stringify(S));}
const kin=id=>S.den.find(e=>e.id===id);
const crew=()=>S.slots.map(id=>kin(id)).filter(Boolean);
const gather=()=>crew().reduce((a,e)=>a+dpsOf(e),0);
const pitPower=()=>S.den.filter(e=>e.job==="pit").reduce((a,e)=>a+atkOf(e),0);
const growBonus=()=>Math.max(0.42,1-S.den.filter(e=>e.job==="hearth").reduce((a,e)=>a+tendOf(e),0));
const veinMax=()=>Math.floor(90*Math.pow(1.24,S.floor-1));
const hatchCost=()=>Math.floor(12+S.hatchCount*6);
const workHit=()=>Math.max(0,gather()*3.2);
const veinName=()=>VEINS[(S.floor-1)%VEINS.length];
function tick(sec){const g=gather();if(g<=0)return;S.cache=Math.min(CAP+S.floor*8,S.cache+g*sec);}
function toast(m){const el=$("#toast");el.textContent=m;el.classList.add("on");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("on"),1300);}
function show(tab){closeSheet();$$(".view").forEach(v=>v.classList.toggle("on",v.dataset.view===tab));$$("nav button").forEach(b=>b.classList.toggle("on",b.dataset.tab===tab));}
function closeSheet(){const s=$("#sheet");s.hidden=true;s.innerHTML="";}
function openSheet(html){const s=$("#sheet");s.hidden=false;s.innerHTML=html;}
function collect(){const amt=Math.floor(S.cache);if(amt<1)return toast("Basin is empty.");S.gold+=amt;S.cache=0;toast("+"+fmt(amt)+" gold");save();render();}
function workHeart(){if(!crew().length)return toast("Seat someone first.");const hit=workHit();S.veinHp=Math.max(0,S.veinHp-hit);S.xp+=2;const h=$("#heart");h.classList.remove("hit");void h.offsetWidth;h.classList.add("hit");if(S.veinHp<=0){S.floor+=1;S.xp+=12;S.ash+=1+Math.floor(S.floor/4);S.veinMax=veinMax();S.veinHp=S.veinMax;toast("Floor "+S.floor);}else toast("\u2212"+hit.toFixed(1)+" on the heart");save();render();}
function hatch(){const c=hatchCost();if(S.cinder<c)return toast("Need "+c+" cinder.");S.cinder-=c;S.hatchCount+=1;S.xp+=6;const baby=makeKin({id:S.nextId++,rarity:pickRarity(S.luck)});const d=dpsOf(baby);let seats="";S.slots.forEach((id,i)=>{const cur=kin(id);const curD=cur?dpsOf(cur):0;const diff=d-curD;seats+="<button data-slot='"+i+"' class='"+(diff>=0?"up":"down")+"'>"+(cur?cur.name:"open")+"<br>"+(diff>=0?"+":"")+diff.toFixed(1)+"</button>";});openSheet("<h3>"+baby.name+"</h3><p>"+baby.rarityLabel+" \u00b7 gathers "+d.toFixed(1)+"/s. Seat them, keep them, or burn for ash.</p><div class='seats'>"+seats+"</div><div class='row'><button id='sellBaby'>Burn \u00b7 +"+(1+baby.bonus)+" ash</button><button id='benchBaby'>Keep in den</button></div>");$$("#sheet [data-slot]").forEach(b=>b.onclick=()=>seat(baby,+b.dataset.slot));$("#sellBaby").onclick=()=>{S.ash+=1+baby.bonus;closeSheet();toast("Ash.");save();render();};$("#benchBaby").onclick=()=>{S.den.unshift(baby);closeSheet();toast("In the den.");save();render();};}
function seat(baby,i){const old=kin(S.slots[i]);if(old)old.job=null;if(!S.den.includes(baby))S.den.unshift(baby);baby.job="well";S.slots[i]=baby.id;closeSheet();toast(baby.name+" seated.");save();render();}
function tapSeat(i){const e=kin(S.slots[i]);if(!e){const free=S.den.filter(k=>!S.slots.includes(k.id));if(!free.length)return hatch();openSheet("<h3>Open stone</h3><p>Who stands here and gathers?</p><div class='seats'>"+free.map(k=>"<button data-id='"+k.id+"'>"+k.name+"<br>"+dpsOf(k).toFixed(1)+"/s</button>").join("")+"</div>");$$("#sheet [data-id]").forEach(b=>b.onclick=()=>seat(kin(+b.dataset.id),i));return;}openSheet("<h3>"+e.name+"</h3><p>"+e.rarityLabel+" \u00b7 lv "+e.lv+" \u00b7 gathers "+dpsOf(e).toFixed(1)+"/s.</p><div class='row'><button id='lvl'>Feed ash \u00b7 "+(2+e.lv)+"</button><button id='pull'>Pull off</button></div>");$("#lvl").onclick=()=>levelKin(e.id);$("#pull").onclick=()=>{e.job=null;S.slots[i]=0;closeSheet();save();render();};}
function levelKin(id){const e=kin(id);if(!e)return;const c=2+e.lv;if(S.ash<c)return toast("Need "+c+" ash.");S.ash-=c;e.lv+=1;e.mult=+(1+(e.lv-1)*0.12).toFixed(2);toast(e.name+" lv "+e.lv);closeSheet();save();render();}
function assign(id,job){const e=kin(id);if(!e)return;if(job==="well"){const empty=S.slots.findIndex(x=>!x);if(empty<0)return toast("Ring is full.");seat(e,empty);return;}S.slots=S.slots.map(x=>x===id?0:x);e.job=e.job===job?null:job;save();render();}
function plantAll(){const crop=CROPS[S.seed];if(S.floor<crop.floor)return toast("Need floor "+crop.floor);const empty=S.plots.filter(p=>p.unlocked&&!p.crop);if(!empty.length)return toast("No open bed.");empty.forEach(p=>{p.crop=S.seed;p.doneAt=Date.now()+Math.floor(crop.ms*growBonus());});save();render();}
function harvestAll(){let n=0;S.plots.forEach(p=>{if(p.crop&&Date.now()>=p.doneAt){S.cinder+=CROPS[p.crop].cinder;p.crop=null;n+=1;}});if(!n)return toast("Nothing ripe.");toast("+"+n+" harvests");save();render();}
function tapPlot(id){const p=S.plots.find(x=>x.id===id);if(!p)return;if(!p.unlocked){if(S.gold<80)return toast("80 gold.");S.gold-=80;p.unlocked=true;save();render();return;}if(p.crop&&Date.now()>=p.doneAt){S.cinder+=CROPS[p.crop].cinder;p.crop=null;save();render();return;}if(!p.crop){const crop=CROPS[S.seed];if(S.floor<crop.floor)return toast("Need floor "+crop.floor);p.crop=S.seed;p.doneAt=Date.now()+Math.floor(crop.ms*growBonus());save();render();}}
function fight(){if(!S.den.some(e=>e.job==="pit"))return toast("Send pit kin from the den.");const you=pitPower();const them=Math.floor((FOES.find(f=>f.id===S.foe)||FOES[0]).power*(1+S.floor*0.04));const win=you+Math.random()*8>=them;S.fights+=1;if(win){const ash=2+Math.floor(them/20);S.ash+=ash;S.gold+=10+S.floor*4;S.rank+=1;if(S.rank%3===0)S.embers+=1;toast("Your den held.");}else toast("They held.");save();render();}
function buyEase(kind){if(kind==="luck"){if(S.embers<3)return toast("3 embers");S.embers-=3;S.luck+=1;}if(kind==="work"){if(S.embers<2)return toast("2 embers");S.embers-=2;workHeart();return;}if(kind==="duel"){if(S.embers<2)return toast("2 embers");S.embers-=2;fight();return;}save();render();}
function claimDaily(){const day=Math.floor(Date.now()/86400000);if(S.lastDaily===day)return toast("Already taken.");S.lastDaily=day;S.embers+=2;toast("+2 embers");save();render();}
function nextRipe(){const now=Date.now(),g=S.plots.filter(p=>p.crop&&p.doneAt>now);if(!g.length)return S.plots.some(p=>p.crop&&p.doneAt<=now)?"ripe":"";return Math.max(0,Math.ceil((Math.min(...g.map(p=>p.doneAt))-now)/1000))+"s";}
function renderHud(){$("#gold").textContent=fmt(S.gold);$("#cinder").textContent=fmt(S.cinder);$("#embersHud").textContent=fmt(S.embers);$("#rate").textContent=gather().toFixed(1)+"/s";$("#floor").textContent="Floor "+S.floor+" \u00b7 slice 9";$("#veinTitle").textContent=veinName();$("#veinHp").textContent=fmt(S.veinHp)+" / "+fmt(S.veinMax||veinMax());$("#veinFill").style.width=Math.max(0,S.veinHp/(S.veinMax||veinMax())*100)+"%";$("#heart").classList.toggle("crew",crew().length>0);$("#rule").textContent=crew().length?("They gather "+gather().toFixed(1)+"/s. Work the heart to go deeper."):"Empty ring. Seat a body or hatch one. Nothing burns on its own.";$("#cacheLbl").textContent=fmt(S.cache)+" in the basin";$("#workLbl").textContent=crew().length?("\u2212"+workHit().toFixed(1)+" per work"):"needs a body";$("#hatchLbl").textContent=hatchCost()+" cinder";$("#navEta").textContent=nextRipe();$("#navPit").textContent=S.rank||"";$("#youLine").textContent="Level "+(1+Math.floor(S.xp/40))+" \u00b7 "+S.den.length+" kin \u00b7 luck "+S.luck+" \u00b7 ash "+fmt(S.ash);}
function renderWell(){$("#crew").innerHTML=S.slots.map((id,i)=>{const e=kin(id);if(!e)return "<button class='seat empty' data-i='"+i+"'><div class='plat'></div><b>open</b><em>seat</em></button>";return "<button class='seat' data-i='"+i+"'><div class='kin kin-"+e.spec+"'></div><div class='plat'></div><b>"+e.name+"</b><em>"+dpsOf(e).toFixed(1)+"/s</em></button>";}).join("");$$("#crew .seat").forEach(b=>b.onclick=()=>tapSeat(+b.dataset.i));}
function renderHearth(){const wrap=$("#plots");wrap.innerHTML="";S.plots.forEach(p=>{const ready=!!(p.crop&&Date.now()>=p.doneAt);const el=document.createElement("button");el.className="hex "+(!p.unlocked?"locked":!p.crop?"":ready?"ripe":"sprout");el.innerHTML="<span>"+(p.crop&&!ready?Math.max(0,Math.ceil((p.doneAt-Date.now())/1000))+"s":ready?"ripe":p.unlocked?"":"sealed")+"</span>";el.onclick=()=>tapPlot(p.id);wrap.appendChild(el);});const row=$("#seedRow");row.innerHTML="";Object.keys(CROPS).forEach(id=>{const c=CROPS[id],b=document.createElement("button");b.className=S.seed===id?"on":"";b.textContent=S.floor<c.floor?c.name+" F"+c.floor:c.name;b.disabled=S.floor<c.floor;b.onclick=()=>{S.seed=id;save();renderHearth();};row.appendChild(b);});const plant=document.createElement("button");plant.textContent="Plant open";plant.onclick=plantAll;row.appendChild(plant);const harv=document.createElement("button");harv.textContent="Pull ripe";harv.onclick=harvestAll;row.appendChild(harv);$("#gardenEta").textContent=nextRipe()==="ripe"?"Beds are ripe.":(nextRipe()?"Next bed "+nextRipe()+".":"The beds wait.");}
function renderPit(){$("#pitRank").textContent=S.rank;const f=FOES.find(x=>x.id===S.foe)||FOES[0];const them=Math.floor(f.power*(1+S.floor*0.04));$("#duel").innerHTML="<div><div class='kin kin-pup'></div><p>"+fmt(pitPower())+" atk</p></div><div class='vs'>vs</div><div><div class='kin kin-fox'></div><p>"+f.name+"<br>"+them+" atk</p></div>";const box=$("#foes");box.innerHTML="";FOES.forEach(foe=>{const el=document.createElement("button");el.textContent=foe.name;if(S.foe===foe.id)el.style.outline="1px solid #e7c56a";el.onclick=()=>{S.foe=foe.id;save();renderPit();};box.appendChild(el);});}
function renderMarket(){$("#ease").innerHTML="<article><b>Luck</b><em>3 embers \u00b7 better hatches</em><br><button data-ease='luck'>Pay</button></article><article><b>Paid strike</b><em>2 embers \u00b7 one work</em><br><button data-ease='work'>Pay</button></article><article><b>Another meeting</b><em>2 embers \u00b7 extra pit fight</em><br><button data-ease='duel'>Pay</button></article>";$$("#ease [data-ease]").forEach(b=>b.onclick=()=>buyEase(b.dataset.ease));}
function renderYou(){const list=$("#cards");list.innerHTML="";S.den.forEach(e=>{const el=document.createElement("article");el.className="card";el.innerHTML="<div class='kin kin-"+e.spec+"'></div><div><b>"+e.name+"</b><p>"+e.rarityLabel+" \u00b7 lv"+e.lv+" \u00b7 "+(e.job||"idle")+"<br>gather "+dpsOf(e).toFixed(1)+"/s \u00b7 atk "+atkOf(e)+"</p></div><div class='jobs'></div>";const jobs=el.querySelector(".jobs");["well","hearth","pit"].forEach(job=>{const b=document.createElement("button");b.textContent=job;if(e.job===job)b.className="on";b.onclick=()=>assign(e.id,job);jobs.appendChild(b);});list.appendChild(el);});}
function render(){renderHud();renderWell();renderHearth();renderPit();renderMarket();renderYou();}
let acc=0;
function loop(ts){if(!loop.last)loop.last=ts;const dt=ts-loop.last;loop.last=ts;acc+=dt;if(acc>220){tick(acc/1000);acc=0;renderHud();if($("[data-view=hearth]").classList.contains("on"))renderHearth();}requestAnimationFrame(loop);}
function boot(){load();const elapsed=Math.min(4*3600*1000,Math.max(0,Date.now()-(S.lastSeen||Date.now())));if(elapsed>2000)tick(elapsed/1000);save();render();show("well");$("#collectBtn").onclick=collect;$("#workBtn").onclick=workHeart;$("#hatchBtn").onclick=hatch;$("#pitBtn").onclick=fight;$("#dailyEmber").onclick=claimDaily;$$("nav button").forEach(b=>b.onclick=()=>show(b.dataset.tab));$("#reset").onclick=()=>{localStorage.removeItem(SAVE);localStorage.removeItem("emberwell.v8");S=defaultState();save();render();};document.addEventListener("pointerdown",e=>{if(!$("#sheet").hidden&&!e.target.closest(".sheet")&&!e.target.closest(".seat"))closeSheet();});requestAnimationFrame(loop);setInterval(save,4000);}
boot();
})();
